### PR TITLE
Vocal tract length perturbation

### LINKED ISSUE #115: Implement Vocal Tract Length Perturbation
It was introduced here: https://arxiv.org/pdf/2011.12536.pdf
VTLP is used in speech recognition (for example: https://arxiv.org/pdf/2201.05562.pdf)

Reference code for vtlp is available here: https://github.com/makcedward/nlpaug/blob/master/nlpaug/model/audio/vtlp.py

### PR DESCRIPTION
**Pull request by akashrajkn**
Implemented VLTP as introduced in http://www.cs.toronto.edu/~hinton/absps/perturb.pdf. Adopted from the numpy code here: https://github.com/makcedward/nlpaug/blob/master/nlpaug/model/audio/vtlp.py

Additional notes:
- Only supports single channel for now
- At the moment, the entire batch will use one (randomized) warp factor
- Added a sanity test case

Fixes #115

### CODE REVIEW

**Comment by iver56** [comment]
Thanks for the pull request :) I'll find time to review this

**Review by iver56 — CHANGES_REQUESTED** [review]
Interesting! I will have another look at this soon, but I've left some initial comments.

I also want to add a mono voice recording in the demo, so I can try it on that.

I understand that this transform does not support stereo/multichannel audio yet. Is that right? Would it be hard to add support for that? The other transforms in torch-audiomentation support multichannel audio

**Comment by iver56** [comment]
I added VTLP to the demo script and added a speech example there:
https://github.com/akashrajkn/torch-audiomentations/pull/1

I listened to the outputs, and it very much resembles a band stop filter. Is that what you intended? I've attached the sounds in this zip:

[vtlp_demo_output.zip](https://github.com/asteroid-team/torch-audiomentations/files/8638202/vtlp_demo_output.zip)

And I have another question: is this a different technique? https://www.isca-speech.org/archive/pdfs/interspeech_2019/kim19_interspeech.pdf

**Comment by iver56** [comment]
vtlp_spectrograms

**Comment by iver56** [comment]
I'm trying to learn about what Vocal Tract Length Perturbation is. Reading the paper, I get the idea that it's about frequency warping

> For VTLP, we generate a random warp factor α for each utterance, and warp the freqency axis, such that a frequency f is mapped to a new frequency f ′

But I don't see frequencies getting re-mapped in the spectrogram gif I posted above

I also found this video online:

https://www.youtube.com/watch?v=vCDnfUM6gn8

Could you try to enlighten me? Do you have some reference examples of what VTLP should sound like? Am I missing something, or is there a bug in your implementation?

**Comment by akashrajkn** [comment]
> I understand that this transform does not support stereo/multichannel audio yet. Is that right?

- [ ] That is right. I will modify it to support stereo audio

> Is that the case here, or is it enough to just use the sample_rate you get from forward calls?

- [ ] You are right, it is not required in the init function. I'll change it accordingly

> And I have another question: is this a different technique? https://www.isca-speech.org/archive/pdfs/interspeech_2019/kim19_interspeech.pdf

I wasn't aware of this paper, I will read it and get back to you

> Do you have some reference examples of what VTLP should sound like?

- [ ] I postponed adding tests in this PR. I will add some reference examples

> Am I missing something, or is there a bug in your implementation?

I think maybe there is an issue with my implementation. I will check it out and comment here (probably on the weekend)

**Comment by iver56** [comment]
Closing for inactivity. Feel free to suggest a reopen later if the work gets picked up again

**Pull request closed without merging**
