### PR TITLE
Padding transform

### PR DESCRIPTION
**Pull request by shahules786**
Added padding transform https://github.com/asteroid-team/torch-audiomentations/issues/91

### CODE REVIEW

**Comment by iver56** [comment]
Thanks for the PR and for the patience :) Reviewing this is still on my TODO list

**Comment by iver56** [comment]
I see two test failures on my end (when running on a CUDA-capable machine)

```
______________________________________________________________ TestPadding.test_Padding_cuda _______________________________________________________________

self = <tests.test_padding.TestPadding testMethod=test_Padding_cuda>

    @pytest.mark.skipif(not torch.cuda.is_available(), reason="Requires CUDA")
    def test_Padding_cuda(self):

        audio_samples = torch.rand(
            size=(2, 2, 32000), dtype=torch.float32, device=torch.device("cuda")
        )
        augment = Padding(min_fraction=0.2, max_fraction=0.5, p=0.5, output_type="dict")
        padded_samples = augment(audio_samples).samples

        self.assertEqual(audio_samples.shape, padded_samples.shape)
>       assert_almost_equal(padded_samples[..., -6400:].numpy(), np.zeros((2, 2, 6400)))
E       TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

tests\test_padding.py:134: TypeError
_________________________________________________________ TestRandomCrop.test_crop_on_device_cuda __________________________________________________________

self = <tests.test_random_crop.TestRandomCrop testMethod=test_crop_on_device_cuda>

    @pytest.mark.skipif(not torch.cuda.is_available(), reason="Requires CUDA")
    def test_crop_on_device_cuda(self):

        samples = torch.rand(
            size=(8, 2, 32000), dtype=torch.float32, device=torch.device("cuda")
        )
        sampling_rate = 16000
        crop_to = 1.5
        desired_samples_len = sampling_rate * crop_to
>       Crop = RandomCrop(
            max_length=crop_to, sampling_rate=sampling_rate, output_type="dict"
        )
E       TypeError: __init__() got an unexpected keyword argument 'output_type'

tests\test_random_crop.py:38: TypeError
```

**Review by iver56 — CHANGES_REQUESTED** [review]
I haven't listened to the outputs yet. I promise to do that later though 😄

**Comment by iver56** [comment]
But the cuda test is still broken. Should I fix it?

**Comment by shahules786** [comment]
@iver56 Oops, my bad. Must be fixed now.

**Comment by iver56** [comment]
Ah, I see. Thanks for the fix 👍

I'm on vacation these days, so response will be slow until at least tuesday. Thanks for your patience :)

**Review by iver56 — APPROVED** [review]
LGTM! It only does zero padding for now, so we could add support for wrap and reflect later

**Pull request merged**
