### PR TITLE
PitchShift augmentation PR, round 3

### PR DESCRIPTION
**Pull request by KentoNishi**

### CODE REVIEW

**Comment by iver56** [comment]
> Currently I'm resampling first, time stretching second. Pretty sure librosa does it the other way. Maybe I should try that?

Have you tried this? The hope is that it could help fix the distortion issue that adds high-frequency harmonics :)

**Comment by KentoNishi** [comment]
I haven't had the chance to, no! I'll do it whenever I'm able to find the time 🙃

**Comment by iver56** [comment]
I can still hear the distortion 😅 If you want to generate and listen to the same example yourself, you can run the demo script after merging this:
https://github.com/KentoNishi/torch-audiomentations/pull/4

**Comment by KentoNishi** [comment]
what's interesting is that the clips i have tried on my own while developing the library sound perfectly acceptable... i wonder what's causing the issue

https://user-images.githubusercontent.com/38841491/128308069-3323b5d5-6e3a-47c8-983e-a38e4815ade0.mp4

**Comment by KentoNishi** [comment]
perfect alley sounds really distorted, can confirm

**Comment by KentoNishi** [comment]
https://user-images.githubusercontent.com/38841491/128314630-b2030edd-d82e-49ea-9d2c-03ac56d60e63.mp4

@iver56 how's this?

**Comment by KentoNishi** [comment]
image

lmaoooooooooooooooo

**Comment by iver56** [comment]
> 
> shifted_ratio_10-9.mp4
> 
> @iver56 how's this?

That definitely sounds less distorted! What did you do?

**Comment by KentoNishi** [comment]
> That definitely sounds less distorted! What did you do?

i added a `hop_length` argument that is calculated using the `sample_rate` by default :D

is speed an issue here? this is still much faster than cpu-based transforms, but significantly slower than the earlier lower-quality transform unfortunately

**Comment by iver56** [comment]
Hmm, having a hop length = n_fft // 32 seems quite extreme indeed. I often have it set to n_fft // 4 when I apply STFT myself

How large can be the hop length be before the quality issue gets too severe? n_fft // 16?

**Comment by KentoNishi** [comment]
`n_fft // 16`

https://user-images.githubusercontent.com/38841491/128319441-803bd45f-a8de-4dc9-9c7e-817c05014dcf.mp4

**Comment by iver56** [comment]
Hmm, yeah, that does add the buzz. I wonder why it needs such a small hop length. Does librosa do this too?

**Comment by KentoNishi** [comment]
https://github.com/librosa/librosa/blob/1468db6d95b276f426935966102f05b86fcc499c/librosa/core/spectrum.py#L1220-L1221

seems like they do `n_fft // 4`. granted, their `n_fft = 2 * (D.shape[0] - 1)`... maybe i should try that idk

**Comment by KentoNishi** [comment]
i can't get it to sound good using the params that the librosa source appears to use... i have to head off to sleep now (and im also very very busy thanks to college applications unfortunately) so i'd appreciate if you could try playing around with it as well. good night!

**Comment by iver56** [comment]
Thanks for your effort! Good night 💤

**Comment by KentoNishi** [comment]
uhhhhhh did it get force pushed again?

**Pull request merged**
